### ISSUE TITLE
未适配的课程类型，请在Github反馈 New Target College English_V2_Video Course 1

### ISSUE THREAD

**Issue by ZZULIXYY** [SSmJaE/WELearnHelper#19]
![image](https://user-images.githubusercontent.com/94783494/146498644-a3247b62-3217-4233-9e6a-9dac4b8b32b1.png)

使用脚本答题时显示：未适配的课程类型，请在Github反馈 New Target College English_V2_Video Course 1

**描述遇到的问题**
反馈使用脚本过程中遇到的问题

**截图**
如果能提供截图，最好提供一下

**你的使用环境**
- 浏览器及版本
  - 如Chrome87
- 脚本管理器:及版本
  - 如tamper monkey 4.11
- 扩展类型与版本
  - 如chrome扩展1.3.4，或油猴脚本1.4.0

**复现**
如何复现你遇到的问题？，比如你是在哪门课程的哪一单元的哪一练习，遇到的bug

**账号提供**
如果能够账号用以调试，有助于解决问题，可以通过qq群私发

**Comment by SSmJaE** [comment]
适配了，试一下
还是不行的话，账号密码发ssmjae327@gmail.com，我上号看一下
