### ISSUE TITLE
未适配的课程类型，请在Github反馈

### ISSUE THREAD

**Issue by 1398726139** [SSmJaE/WELearnHelper#27]
New Target College English_V2_Video Course 4
![屏幕截图 2022-03-15 182829](https://user-images.githubusercontent.com/98800429/158358300-218a2288-d6a9-43c4-b9e9-18c8b1270d13.png)

**Comment by SSmJaE** [comment]
适配了，试一下
还是不行的话，账号密码发ssmjae327@gmail.com，我上号看一下
