### ISSUE TITLE
未适配的课程类型

### ISSUE THREAD

**Issue by djr2002** [SSmJaE/WELearnHelper#28]
**描述遇到的问题**新目标大学英语视听说2和综合教程二答案搜不出来
反馈使用脚本过程中遇到的问题

**截图**
如果能提供截图，最好提供一下
**你的使用环境**
- 浏览器及版本
  版本 5.1.3.22 （32 位）
  内核版本: Chromium 86.0.4240.198  +  IE (Trident 7~11)
- 脚本管理器:及版本
  - tamper monkey4.8.41
- 扩展类型与版本
  - 如chrome扩展1.3.4，或油猴脚本1.4.0

**复现**
如何复现你遇到的问题？，比如你是在哪门课程的哪一单元的哪一练习，遇到的bug

**账号提供**
如果能够账号用以调试，有助于解决问题，可以通过qq群私发

**Comment by SSmJaE** [comment]
适配了，试一下
还是不行的话，账号密码发ssmjae327@gmail.com，我上号看一下
