### ISSUE TITLE
未适配的课程类型，请在Github反馈

### ISSUE THREAD

**Issue by BKCake** [SSmJaE/WELearnHelper#40]
New Target College English_V2_Integrated Course 2
![image](https://user-images.githubusercontent.com/61220345/198817652-1baadd62-9534-4561-b3a0-b10957ab1407.png)

**Comment by SSmJaE** [comment]
私发一下账密到[ssmjae327@gmail.com](mailto:ssmjae327@gmail.com)，适配用

**Comment by mlstudyhard** [comment]
新世纪大学英语系列教材（第二版）视听说教程（3rd Edition）这个好像没有适配啊

**Comment by SSmJaE** [comment]
> 新世纪大学英语系列教材（第二版）视听说教程（3rd Edition）这个好像没有适配啊

适配了
