### ISSUE TITLE
双击无法重新打开

### ISSUE THREAD

**Issue by 2085886325** [SSmJaE/WELearnHelper#42]
**描述遇到的问题**
反馈使用脚本过程中遇到的问题
双击关闭后无法双击再打开，除非刷新重载
**截图**
如果能提供截图，最好提供一下
![image](https://user-images.githubusercontent.com/61336743/201503915-3d90c051-92ac-4427-bc5b-5b666397360b.png)

**你的使用环境**
- 浏览器及版本
  - 如Chrome87
  - QQ浏览器94.0.4606.71
- 脚本管理器:及版本
  - 如tamper monkey 4.11
  - 未知
- 扩展类型与版本
  - 如chrome扩展1.3.4，或油猴脚本1.4.0

**复现**
如何复现你遇到的问题？，比如你是在哪门课程的哪一单元的哪一练习，遇到的bug

**账号提供**
如果能够账号用以调试，有助于解决问题，可以通过qq群私发

**Comment by SSmJaE** [comment]
用新版本解决
