### ISSUE TITLE
未有适配课程类型

### ISSUE THREAD

**Issue by zxttx** [SSmJaE/WELearnHelper#48]
**描述遇到的问题**未有适配课程类型
反馈使用脚本过程中遇到的问题

**截图**
![图片](https://user-images.githubusercontent.com/126858183/222660407-2a0ca62f-492e-4616-ad2c-c76512681e5e.png)

如果能提供截图，最好提供一下

**你的使用环境**
- 浏览器及版本
  - 如firefok110.0
- 脚本管理器:及版本
  - 如tamper monkey 4.18.1
- 扩展类型与版本
  - 油猴脚本4.18.1

**复现**
如何复现你遇到的问题？，比如你是在哪门课程的哪一单元的哪一练习，遇到的bug

**账号提供**
如果能够账号用以调试，有助于解决问题，可以通过qq群私发

**Comment by SSmJaE** [comment]
这个版本太古早了，用新版本试一试，如果还存在，再联系我
