### ISSUE TITLE
更新后练习题库查询不出来

### ISSUE THREAD

**Issue by MOONKEEPER001** [SSmJaE/WELearnHelper#52]
**描述遇到的问题**
未更新前还能查到练习题题库，更新后查不到了

**截图**
![image](https://user-images.githubusercontent.com/101966913/226368285-edfe2a03-878e-4543-ba1b-3b385a904e2e.png)

**你的使用环境**
- 浏览器及版本
  Chrome 111.0.5563.65（正式版本） （64 位）
- 脚本管理器:及版本
  - 如tamper monkey 4.18.1
- 扩展类型与版本
  - 脚本1.0.1

**复现**
全新版大学进阶英语：视听说教程第二册 练习任务三

**账号提供**

**Comment by TWLW9784** [comment]
同意的问题，也查不出答案了

**Comment by TWLW9784** [comment]
求更新
