### ISSUE TITLE
界面被题目遮住

### ISSUE THREAD

**Issue by LeoStr4nge** [SSmJaE/WELearnHelper#53]
**描述遇到的问题**
助手的界面被题目的界面遮住了，只能拖到空白处查看和点击。
**截图**
如果能提供截图，最好提供一下
![image](https://user-images.githubusercontent.com/115483270/226828642-2f7ca74e-c59e-499b-9676-91cf3637b7b2.png)
**你的使用环境**
Microsoft Edge111.0.1661.44
- 脚本管理器:及版本
 tamper monkey 4.18.1
**复现**
用的教材是《全新版大学进阶英语：视听说教程2》，更新成新版之后就出现了这个问题。

**Comment by SSmJaE** [comment]
1.0.3已修复
