### ISSUE TITLE
1.0.3如何无限播放听力？

### ISSUE THREAD

**Issue by YorkWaugh** [SSmJaE/WELearnHelper#54]
**描述遇到的问题**
无限播放听力功能消失，答案界面只能播放问题音频，无法重播原文音频

**你的使用环境**
- 浏览器及版本
  - Chrome111
- 脚本管理器:及版本
  - tamper monkey 4.18.1
- 扩展类型与版本
  - 油猴脚本1.0.3

**Comment by SSmJaE** [comment]
我看看

**Comment by YorkWaugh** [comment]
> 我看看 老版本可以正常播放吗？

在1.0版本前是正常的，改了UI后就不行了。我现在也没有老师布置的作业，没办法再去测试。

**Comment by SSmJaE** [comment]
试一下1.0.4

**Comment by YorkWaugh** [comment]
> 试一下1.0.4

已可以正常播放了，谢谢！
