### ISSUE TITLE
答案未收录

### ISSUE THREAD

**Issue by 44672** [SSmJaE/WELearnHelper#55]
**描述遇到的问题**
全新版大学进阶英语：综合教程2（思政智慧版）的课后单元测试部分，查询之后显示“尚未收录答案”

**截图**
![屏幕截图 2023-03-30 230702](https://user-images.githubusercontent.com/129411140/228880959-3cf12033-a46e-4ac7-99e1-4856c363cb68.png)

**你的使用环境**
- 浏览器及版本
  -Edge 111.0.1661.54 
- 脚本管理器:及版本
  - tamper monkey 4.18.1
- 扩展类型与版本
  - chrome扩展1.0.3

**复现**
各个单元测试都会出现这个问题，大部分题目会显示尚未收录答案
**账号提供**
如果能够账号用以调试，有助于解决问题，可以通过qq群私发

**Comment by SSmJaE** [comment]
私发下账号
ssmjae327@gmail.com
