### ISSUE TITLE
No answer found

### ISSUE THREAD

**Issue by xiaozhanghexiaozhou** [SSmJaE/WELearnHelper#59]
![image](https://github.com/SSmJaE/WELearnHelper/assets/133929646/a811c9b7-6f9b-4513-8952-eebc10f8c9f1)

**Comment by SSmJaE** [comment]
升级1.0.5，这个版本太旧了

**Comment by xiaozhanghexiaozhou** [comment]
怎么升级啊

**Comment by xiaozhanghexiaozhou** [comment]
![image](https://github.com/SSmJaE/WELearnHelper/assets/133929646/a0402cbc-52b1-45d5-82dd-2a354d88e373)
这就是最新的啊
