### ISSUE TITLE
答案未收录

### ISSUE THREAD

**Issue by xiaozhanghexiaozhou** [SSmJaE/WELearnHelper#61]
## 答案未收录

反馈使用脚本过程中遇到的问题

## ![image](https://github.com/SSmJaE/WELearnHelper/assets/133929646/db5e280c-dee6-44db-90f4-e6b39baa7975)
![image](https://github.com/SSmJaE/WELearnHelper/assets/133929646/5d893978-080b-4776-b292-d2d3d29e92bd)

如果能提供截图，最好提供一下

**Comment by SSmJaE** [comment]
让已经做完的同学上传一下
