### ISSUE TITLE
答案未收录

### ISSUE THREAD

**Issue by liulifeili** [SSmJaE/WELearnHelper#63]
## 截图
![1694441539740](https://github.com/SSmJaE/WELearnHelper/assets/72261190/dc735e78-3363-41f9-8303-9294fe6a2330)

## 你的使用环境

- 浏览器及版本
  - Edge 114.0.1823.79 (正式版本) (64 位)
- 脚本管理器及版本
  - Tampermonkey 4.19.0
- 扩展类型与版本
  - 油猴脚本1.0.5

**Comment by SSmJaE** [comment]
让已经做完的同学上传一下
