### ISSUE TITLE
刷时长功能失效

### ISSUE THREAD

**Issue by wba280** [SSmJaE/WELearnHelper#65]
## 描述遇到的问题

反馈使用脚本过程中遇到的问题

## 截图

如果能提供截图，最好提供一下

## 你的使用环境

- 浏览器及版本
  - 如Chrome 111
- 脚本管理器及版本
  - 如tamper monkey 4.11，或者脚本猫
- 扩展类型与版本
  - 如chrome扩展1.0.5，或油猴脚本1.0.5

## 复现

如何复现你遇到的问题？比如你是在哪门课程的哪一单元的哪一练习，遇到的bug

## 账号提供

如果能够账号用以调试，有助于解决问题，可以通过邮箱私发我

ssmjae327@gmail.com

**Comment by SSmJaE** [comment]
需要账号进行测试

**Comment by SSmJaE** [comment]
合并到 #60
