### ISSUE TITLE
全新版大学高阶英语听说教程（第三版）2未适配

### ISSUE THREAD

**Issue by xiangxianggancao** [SSmJaE/WELearnHelper#66]
## 描述遇到的问题

反馈使用脚本过程中遇到的问题

## 截图
![capture_20231011160607089](https://github.com/SSmJaE/WELearnHelper/assets/147595480/4b451845-0fd4-4dcb-b531-c373c7d11088)

## 你的使用环境

- 浏览器及版本
  - 如Chrome 111
- 脚本管理器及版本
  - 如tamper monkey 4.11，或者脚本猫
- 扩展类型与版本
  - 如chrome扩展1.0.5，或油猴脚本1.0.5

## 复现

如何复现你遇到的问题？比如你是在哪门课程的哪一单元的哪一练习，遇到的bug

## 账号提供

如果能够账号用以调试，有助于解决问题，可以通过邮箱私发我

ssmjae327@gmail.com

**Comment by SSmJaE** [comment]
适配了
