### ISSUE TITLE
大佬还准备扩展一下支持的课吗

### ISSUE THREAD

**Issue by LineCatOvO** [SSmJaE/WELearnHelper#67]
视听说第四版和以前的旧版区别还蛮大，不过应该还是可以做自动答题脚本吧，或者至少弄个答案显示，比如这里的填空题，devtool下能看到刷新前后id是不变的，不过也可能受用户信息影响？直接在span中插文字也能输上去，仅答案显示的话希望url能帮忙定位是哪一个作业，但是做起来很麻烦吧。有现在这个效果已经很强了。
![图片](https://github.com/SSmJaE/WELearnHelper/assets/126733379/ac57207b-118d-4d30-acc2-6364c7c59ea2)

**Comment by SSmJaE** [comment]
你用的版本好古早，可以升级到新版本了

来个账号，我测试测试
