### ISSUE TITLE
Welearn新出的WeTest 插件无法显示并使用

### ISSUE THREAD

**Issue by liulifeili** [SSmJaE/WELearnHelper#75]
## 描述遇到的问题

Welearn新出的WeTest 插件无法显示并使用

## 截图

![image](https://github.com/SSmJaE/WELearnHelper/assets/72261190/90728b60-f475-432f-b54e-1ebb920a8e5d)

## 你的使用环境

- 浏览器及版本
  - Microsoft Edge 121.0.2277.112
- 脚本管理器及版本
  - tamper monkey 5.0.1

## 复现

就是打开任务的测试就会这样

## 账号提供

账号目前需要做题，目前无法提供

**Comment by SSmJaE** [comment]
[v1.1.0](https://github.com/SSmJaE/WELearnHelper/releases/tag/v1.1.0)已修复，还有问题再反馈
