### ISSUE TITLE
feat：对使用相同特定框架、未适配的课程类型(练习)进行暴力修改以显示答案

### ISSUE THREAD

**Issue by mcitem** [SSmJaE/WELearnHelper#78]
对于新视野 视听说教程系列，推测可能使用的都是相同的框架，目前最新版对新视野大学英语《视听说教程(第四版)2》显示不支持的课程类型(并非app题)

除了强制使用app进行录音的课程、主观答题练习以外，基本都可以暴力修改class让controls中的key和script按键暴露出来，然后在直接点击key显示官方的答案校验工具，此时可直接copy答案并提交

以下是暴力修改的位置(仅限课程练习，测试不可用)
```
body
-- div class="courseware_main"
-- -- iframe class="contentFrame"
-- -- --  # document
-- -- -- -- html
-- -- -- -- -- body
-- -- -- -- -- -- div class="wrapper"
-- -- -- -- -- -- -- div ui-view class="main"
-- -- -- -- -- -- -- -- div class="seo"
-- -- -- -- -- -- -- -- -- div class="controls"
-- -- -- -- -- -- -- -- -- -- div class="sub"
```
只要暴力地将sub类名删掉或者改成sub1就可以让官方的校对按钮暴露出来
这种方法是否更适合用于显示练习的答案？
当然也只限于使用相同课程框架的书

或者是脚本自动去触发key按钮下的事件？

**Comment by SSmJaE** [comment]
合理的猜测
来个账号我试试？

**Comment by mcitem** [comment]
> 合理的猜测 来个账号我试试？

提供了一个可用的激活码给你（
已经发到邮箱 ssmjae327@gmail.com
对应的书是“新视野大学英语视听说教程（第四版）1 ”

修改类名显示的方法在这本书的练习中一样有用

**Comment by mcitem** [comment]
这个想法在操作上比较简单，下面是一个手动修改演示的视频
https://github.com/SSmJaE/WELearnHelper/assets/124600270/eef2b5b5-10c0-4c61-95f5-94979bc03097
